<template>
    <div></div>
</template>

<script>
const catalogData = [
    {
        image: "orange.jpg",
        name: "Fresh Oranges",
        type: "Фрукты",
        starsProduct: 4,
        price: 300.00,
        maxItems: 300,
        sellerStars: 5,
        reviews: 17,
        article: "6215920-1-2",
        detail: "Описание продукта 1",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Armenia',
        brand: 'Gainzo',
        freeDelivery: true,
        weight: ['200', '300'],
        attributes: ['noSeed', 'spicy']
    },
    {
        image: "orange.jpg",
        name: "Dried Apricots",
        type: "Сухофрукты",
        starsProduct: 5,
        price: 450.00,
        maxItems: 150,
        sellerStars: 4,
        reviews: 23,
        article: "6215921",
        detail: "Сушеные абрикосы высшего качества",
        status: ['available'],
        deliveryCities: ['Krasnodar'],
        country: 'Armenia',
        brand: 'Rawshop',
        freeDelivery: false,
        weight: ['300', '500'],
        attributes: ['noSeed']
    },
    {
        image: "orange.jpg",
        name: "Roasted Almonds",
        type: "Орехи",
        starsProduct: 5,
        price: 890.00,
        maxItems: 100,
        sellerStars: 5,
        reviews: 42,
        article: "6215922",
        detail: "Жареный миндаль с солью",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Kazan', 'Krasnodar'],
        country: 'Kazakhstan',
        brand: 'Gainzo',
        freeDelivery: true,
        weight: ['200', '400'],
        attributes: ['fried', 'spicy']
    },
    {
        image: "orange.jpg",
        name: "Green Tea",
        type: "Кофе и чай",
        starsProduct: 4,
        price: 250.00,
        maxItems: 200,
        sellerStars: 4,
        reviews: 15,
        article: "6215923",
        detail: "Зеленый чай высшего сорта",
        status: ['available'],
        deliveryCities: ['Voronezh'],
        country: 'Kazakhstan',
        brand: 'Martstore',
        freeDelivery: false,
        weight: ['200'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Exotic Mango",
        type: "Экзотика",
        starsProduct: 5,
        price: 780.00,
        maxItems: 50,
        sellerStars: 5,
        reviews: 28,
        article: "6215924",
        detail: "Спелое манго премиум качества",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Krasnodar'],
        country: 'Armenia',
        brand: 'XBekery',
        freeDelivery: true,
        weight: ['400', '500'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Salted Cashews",
        type: "Орехи",
        starsProduct: 4,
        price: 1200.00,
        maxItems: 80,
        sellerStars: 4,
        reviews: 19,
        article: "6215925",
        detail: "Кешью солёные",
        status: ['available'],
        deliveryCities: ['Kazan'],
        country: 'Kazakhstan',
        brand: 'Martstore',
        freeDelivery: false,
        weight: ['200', '300', '500'],
        attributes: ['fried', 'spicy']
    },
    {
        image: "orange.jpg",
        name: "Fresh Tomatoes",
        type: "Овощи",
        starsProduct: 5,
        price: 320.00,
        maxItems: 200,
        sellerStars: 5,
        reviews: 31,
        article: "6215926",
        detail: "Свежие томаты",
        status: ['available'],
        deliveryCities: ['Voronezh', 'Krasnodar'],
        country: 'Russia',
        brand: 'Gainzo',
        freeDelivery: true,
        weight: ['500', '600'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Black Tea",
        type: "Кофе и чай",
        starsProduct: 4,
        price: 280.00,
        maxItems: 150,
        sellerStars: 4,
        reviews: 12,
        article: "6215927",
        detail: "Чёрный чай высшего сорта",
        status: ['outOfStock'],
        deliveryCities: ['Kazan'],
        country: 'Kazakhstan',
        brand: 'Rawshop',
        freeDelivery: false,
        weight: ['200'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Mixed Dried Fruits",
        type: "Сухофрукты",
        starsProduct: 5,
        price: 550.00,
        maxItems: 100,
        sellerStars: 5,
        reviews: 25,
        article: "6215928",
        detail: "Ассорти сухофруктов",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Krasnodar', 'Kazan'],
        country: 'Armenia',
        brand: 'XBekery',
        freeDelivery: true,
        weight: ['300', '400'],
        attributes: ['noSeed']
    },
    {
        image: "orange.jpg",
        name: "Premium Coffee Beans",
        type: "Кофе и чай",
        starsProduct: 5,
        price: 890.00,
        maxItems: 100,
        sellerStars: 5,
        reviews: 45,
        article: "6215929",
        detail: "Премиальные кофейные зерна",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Kazan', 'Krasnodar'],
        country: 'Armenia',
        brand: 'Rawshop',
        freeDelivery: true,
        weight: ['200', '500'],
        attributes: ['fried']
    },
    {
        image: "orange.jpg",
        name: "Organic Pistachios",
        type: "Орехи",
        starsProduct: 4,
        price: 1500.00,
        maxItems: 50,
        sellerStars: 4,
        reviews: 33,
        article: "6215930",
        detail: "Органические фисташки",
        status: ['available'],
        deliveryCities: ['Krasnodar'],
        country: 'Kazakhstan',
        brand: 'XBekery',
        freeDelivery: false,
        weight: ['300', '400'],
        attributes: ['fried', 'spicy']
    },
    {
        image: "orange.jpg",
        name: "Organic Dates",
        type: "Сухофрукты",
        starsProduct: 5,
        price: 420.00,
        maxItems: 120,
        sellerStars: 5,
        reviews: 38,
        article: "6215931",
        detail: "Органические финик",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Armenia',
        brand: 'Gainzo',
        freeDelivery: true,
        weight: ['200', '400'],
        attributes: ['noSeed']
    },
    {
        image: "orange.jpg",
        name: "Fresh Cucumbers",
        type: "Овощи",
        starsProduct: 4,
        price: 180.00,
        maxItems: 250,
        sellerStars: 4,
        reviews: 22,
        article: "6215932",
        detail: "Свежие огурцы",
        status: ['available'],
        deliveryCities: ['Krasnodar', 'Kazan'],
        country: 'Russia',
        brand: 'Martstore',
        freeDelivery: false,
        weight: ['500', '600'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Spiced Almonds",
        type: "Орехи",
        starsProduct: 5,
        price: 950.00,
        maxItems: 80,
        sellerStars: 5,
        reviews: 29,
        article: "6215933",
        detail: "Миндаль со специями",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh'],
        country: 'Kazakhstan',
        brand: 'XBekery',
        freeDelivery: true,
        weight: ['200', '300'],
        attributes: ['fried', 'spicy']
    },
    {
        image: "orange.jpg",
        name: "Herbal Tea Mix",
        type: "Кофе и чай",
        starsProduct: 5,
        price: 340.00,
        maxItems: 150,
        sellerStars: 4,
        reviews: 27,
        article: "6215934",
        detail: "Травяной чайный сбор",
        status: ['available'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Russia',
        brand: 'Martstore',
        freeDelivery: true,
        weight: ['200', '300'],
        attributes: ['spicy']
    },
    {
        image: "orange.jpg",
        name: "Fresh Strawberries",
        type: "Ягоды",
        starsProduct: 5,
        price: 420.00,
        maxItems: 100,
        sellerStars: 5,
        reviews: 34,
        article: "6215935",
        detail: "Свежая клубника",
        status: ['available', 'onSale'],
        deliveryCities: ['Krasnodar'],
        country: 'Russia',
        brand: 'Gainzo',
        freeDelivery: true,
        weight: ['300', '500'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Fresh Raspberries",
        type: "Ягоды",
        starsProduct: 5,
        price: 650.00,
        maxItems: 80,
        sellerStars: 5,
        reviews: 41,
        article: "6215936",
        detail: "Свежая малина",
        status: ['available'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Russia',
        brand: 'Gainzo',
        freeDelivery: true,
        weight: ['200', '300'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Dried Figs",
        type: "Сухофрукты",
        starsProduct: 4,
        price: 480.00,
        maxItems: 150,
        sellerStars: 4,
        reviews: 19,
        article: "6215937",
        detail: "Сушеный инжир",
        status: ['available', 'onSale'],
        deliveryCities: ['Krasnodar', 'Kazan'],
        country: 'Armenia',
        brand: 'XBekery',
        freeDelivery: false,
        weight: ['300', '400', '500'],
        attributes: ['noSeed']
    },
    {
        image: "orange.jpg",
        name: "Premium Walnuts",
        type: "Орехи",
        starsProduct: 5,
        price: 850.00,
        maxItems: 120,
        sellerStars: 5,
        reviews: 31,
        article: "6215938",
        detail: "Отборные грецкие орехи",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Krasnodar'],
        country: 'Armenia',
        brand: 'Gainzo',
        freeDelivery: true,
        weight: ['200', '400', '500'],
        attributes: ['fried']
    },
    {
        image: "orange.jpg",
        name: "Fresh Bell Peppers",
        type: "Овощи",
        starsProduct: 4,
        price: 280.00,
        maxItems: 200,
        sellerStars: 4,
        reviews: 25,
        article: "6215939",
        detail: "Свежий болгарский перец",
        status: ['available'],
        deliveryCities: ['Kazan', 'Krasnodar'],
        country: 'Russia',
        brand: 'Martstore',
        freeDelivery: false,
        weight: ['500', '600'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Fresh Carrots",
        type: "Овощи",
        starsProduct: 4,
        price: 160.00,
        maxItems: 300,
        sellerStars: 4,
        reviews: 28,
        article: "6215940",
        detail: "Свежая морковь",
        status: ['available'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Russia',
        brand: 'Gainzo',
        freeDelivery: false,
        weight: ['500', '600'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Organic Honey",
        type: "Сладости",
        starsProduct: 5,
        price: 890.00,
        maxItems: 50,
        sellerStars: 5,
        reviews: 45,
        article: "6215941",
        detail: "Органический мед",
        status: ['available', 'onSale'],
        deliveryCities: ['Krasnodar'],
        country: 'Armenia',
        brand: 'XBekery',
        freeDelivery: true,
        weight: ['200', '300', '500'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Fresh Blueberries",
        type: "Ягоды",
        starsProduct: 5,
        price: 580.00,
        maxItems: 90,
        sellerStars: 4,
        reviews: 36,
        article: "6215942",
        detail: "Свежая голубика",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Russia',
        brand: 'Gainzo',
        freeDelivery: true,
        weight: ['200', '300'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Dried Cranberries",
        type: "Сухофрукты",
        starsProduct: 4,
        price: 390.00,
        maxItems: 200,
        sellerStars: 5,
        reviews: 28,
        article: "6215943",
        detail: "Сушеная клюква",
        status: ['available'],
        deliveryCities: ['Krasnodar', 'Kazan'],
        country: 'Russia',
        brand: 'XBekery',
        freeDelivery: false,
        weight: ['200', '400', '500'],
        attributes: ['noSeed']
    },
    {
        image: "orange.jpg",
        name: "Roasted Peanuts",
        type: "Орехи",
        starsProduct: 5,
        price: 450.00,
        maxItems: 150,
        sellerStars: 4,
        reviews: 42,
        article: "6215944",
        detail: "Жареный арахис",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh'],
        country: 'Kazakhstan',
        brand: 'Martstore',
        freeDelivery: true,
        weight: ['300', '500'],
        attributes: ['fried', 'spicy']
    },
    {
        image: "orange.jpg",
        name: "Fresh Broccoli",
        type: "Овощи",
        starsProduct: 4,
        price: 220.00,
        maxItems: 180,
        sellerStars: 5,
        reviews: 19,
        article: "6215945",
        detail: "Свежая брокколи",
        status: ['available'],
        deliveryCities: ['Krasnodar', 'Kazan'],
        country: 'Russia',
        brand: 'Gainzo',
        freeDelivery: false,
        weight: ['500', '600'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Dragon Fruit",
        type: "Экзотика",
        starsProduct: 5,
        price: 890.00,
        maxItems: 40,
        sellerStars: 4,
        reviews: 31,
        article: "6215946",
        detail: "Питахайя (Dragon Fruit)",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Armenia',
        brand: 'XBekery',
        freeDelivery: true,
        weight: ['300', '400'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Masala Chai",
        type: "Кофе и чай",
        starsProduct: 5,
        price: 420.00,
        maxItems: 100,
        sellerStars: 5,
        reviews: 47,
        article: "6215947",
        detail: "Индийский масала чай",
        status: ['available'],
        deliveryCities: ['Voronezh', 'Krasnodar'],
        country: 'Armenia',
        brand: 'Rawshop',
        freeDelivery: true,
        weight: ['200', '300'],
        attributes: ['spicy']
    },
    {
        image: "orange.jpg",
        name: "Chocolate Covered Almonds",
        type: "Сладости",
        starsProduct: 5,
        price: 750.00,
        maxItems: 80,
        sellerStars: 4,
        reviews: 39,
        article: "6215948",
        detail: "Миндаль в шоколаде",
        status: ['available', 'onSale'],
        deliveryCities: ['Kazan', 'Krasnodar'],
        country: 'Kazakhstan',
        brand: 'XBekery',
        freeDelivery: true,
        weight: ['200', '300', '400'],
        attributes: ['fried']
    },
    {
        image: "orange.jpg",
        name: "Dried Mango Strips",
        type: "Чипсы - слайсы",
        starsProduct: 4,
        price: 380.00,
        maxItems: 120,
        sellerStars: 5,
        reviews: 33,
        article: "6215949",
        detail: "Сушеные полоски манго",
        status: ['available'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Armenia',
        brand: 'Martstore',
        freeDelivery: false,
        weight: ['200', '300'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Saffron",
        type: "Травы и специи",
        starsProduct: 5,
        price: 1900.00,
        maxItems: 30,
        sellerStars: 5,
        reviews: 25,
        article: "6215950",
        detail: "Шафран высшего качества",
        status: ['available', 'onSale'],
        deliveryCities: ['Krasnodar'],
        country: 'Armenia',
        brand: 'Rawshop',
        freeDelivery: true,
        weight: ['100', '200'],
        attributes: ['spicy']
    },
    {
        image: "orange.jpg",
        name: "Goji Berries",
        type: "Сухофрукты",
        starsProduct: 5,
        price: 990.00,
        maxItems: 70,
        sellerStars: 4,
        reviews: 29,
        article: "6215951",
        detail: "Ягоды годжи премиум качества",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Armenia',
        brand: 'Rawshop',
        freeDelivery: true,
        weight: ['200', '300'],
        attributes: ['noSeed']
    },
    {
        image: "orange.jpg",
        name: "Macadamia Nuts",
        type: "Орехи",
        starsProduct: 5,
        price: 2100.00,
        maxItems: 50,
        sellerStars: 5,
        reviews: 34,
        article: "6215952",
        detail: "Орехи макадамия",
        status: ['available'],
        deliveryCities: ['Krasnodar'],
        country: 'Kazakhstan',
        brand: 'XBekery',
        freeDelivery: true,
        weight: ['200', '300', '500'],
        attributes: ['fried']
    },
    {
        image: "orange.jpg",
        name: "Fresh Asparagus",
        type: "Овощи",
        starsProduct: 4,
        price: 450.00,
        maxItems: 100,
        sellerStars: 4,
        reviews: 22,
        article: "6215953",
        detail: "Свежая спаржа",
        status: ['available'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Russia',
        brand: 'Gainzo',
        freeDelivery: false,
        weight: ['300', '500'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Durian",
        type: "Экзотика",
        starsProduct: 4,
        price: 3500.00,
        maxItems: 20,
        sellerStars: 5,
        reviews: 15,
        article: "6215954",
        detail: "Свежий дуриан",
        status: ['available', 'onSale'],
        deliveryCities: ['Krasnodar'],
        country: 'Armenia',
        brand: 'XBekery',
        freeDelivery: true,
        weight: ['1000', '2000'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Oolong Tea",
        type: "Кофе и чай",
        starsProduct: 5,
        price: 890.00,
        maxItems: 60,
        sellerStars: 5,
        reviews: 41,
        article: "6215955",
        detail: "Чай улун высшего сорта",
        status: ['available'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Armenia',
        brand: 'Rawshop',
        freeDelivery: true,
        weight: ['100', '200'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Turkish Delight",
        type: "Сладости",
        starsProduct: 5,
        price: 450.00,
        maxItems: 150,
        sellerStars: 4,
        reviews: 38,
        article: "6215956",
        detail: "Рахат-лукум",
        status: ['available', 'onSale'],
        deliveryCities: ['Krasnodar', 'Kazan'],
        country: 'Armenia',
        brand: 'XBekery',
        freeDelivery: false,
        weight: ['300', '500'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Apple Chips",
        type: "Чипсы - слайсы",
        starsProduct: 4,
        price: 280.00,
        maxItems: 200,
        sellerStars: 4,
        reviews: 27,
        article: "6215957",
        detail: "Яблочные чипсы",
        status: ['available'],
        deliveryCities: ['Voronezh'],
        country: 'Russia',
        brand: 'Martstore',
        freeDelivery: false,
        weight: ['100', '200'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Cardamom",
        type: "Травы и специи",
        starsProduct: 5,
        price: 790.00,
        maxItems: 80,
        sellerStars: 5,
        reviews: 31,
        article: "6215958",
        detail: "Кардамон в стручках",
        status: ['available'],
        deliveryCities: ['Krasnodar', 'Kazan'],
        country: 'Armenia',
        brand: 'Rawshop',
        freeDelivery: true,
        weight: ['50', '100'],
        attributes: ['spicy']
    },
    {
        image: "orange.jpg",
        name: "Fresh Blackberries",
        type: "Ягоды",
        starsProduct: 5,
        price: 490.00,
        maxItems: 100,
        sellerStars: 4,
        reviews: 29,
        article: "6215959",
        detail: "Свежая ежевика",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Russia',
        brand: 'Gainzo',
        freeDelivery: true,
        weight: ['200', '300'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Dried Pineapple",
        type: "Сухофрукты",
        starsProduct: 4,
        price: 420.00,
        maxItems: 150,
        sellerStars: 5,
        reviews: 33,
        article: "6215960",
        detail: "Сушеный ананас",
        status: ['available'],
        deliveryCities: ['Krasnodar'],
        country: 'Armenia',
        brand: 'XBekery',
        freeDelivery: false,
        weight: ['200', '300', '500'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Pine Nuts",
        type: "Орехи",
        starsProduct: 5,
        price: 2500.00,
        maxItems: 40,
        sellerStars: 5,
        reviews: 26,
        article: "6215961",
        detail: "Кедровые орехи",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Russia',
        brand: 'Gainzo',
        freeDelivery: true,
        weight: ['100', '200', '300'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Fresh Artichokes",
        type: "Овощи",
        starsProduct: 4,
        price: 590.00,
        maxItems: 80,
        sellerStars: 4,
        reviews: 19,
        article: "6215962",
        detail: "Свежие артишоки",
        status: ['available'],
        deliveryCities: ['Krasnodar'],
        country: 'Armenia',
        brand: 'Martstore',
        freeDelivery: false,
        weight: ['500', '1000'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Passion Fruit",
        type: "Экзотика",
        starsProduct: 5,
        price: 690.00,
        maxItems: 70,
        sellerStars: 5,
        reviews: 28,
        article: "6215963",
        detail: "Маракуйя свежая",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Armenia',
        brand: 'XBekery',
        freeDelivery: true,
        weight: ['300', '500'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Ethiopian Coffee",
        type: "Кофе и чай",
        starsProduct: 5,
        price: 1200.00,
        maxItems: 50,
        sellerStars: 5,
        reviews: 45,
        article: "6215964",
        detail: "Эфиопский кофе в зернах",
        status: ['available'],
        deliveryCities: ['Krasnodar', 'Kazan'],
        country: 'Armenia',
        brand: 'Rawshop',
        freeDelivery: true,
        weight: ['250', '500'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Halva",
        type: "Сладости",
        starsProduct: 4,
        price: 350.00,
        maxItems: 120,
        sellerStars: 4,
        reviews: 31,
        article: "6215965",
        detail: "Халва подсолнечная",
        status: ['available'],
        deliveryCities: ['Voronezh'],
        country: 'Kazakhstan',
        brand: 'XBekery',
        freeDelivery: false,
        weight: ['200', '400'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Beetroot Chips",
        type: "Чипсы - слайсы",
        starsProduct: 4,
        price: 290.00,
        maxItems: 150,
        sellerStars: 4,
        reviews: 24,
        article: "6215966",
        detail: "Свекольные чипсы",
        status: ['available', 'onSale'],
        deliveryCities: ['Krasnodar', 'Kazan'],
        country: 'Russia',
        brand: 'Martstore',
        freeDelivery: false,
        weight: ['100', '200'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Star Anise",
        type: "Травы и специи",
        starsProduct: 5,
        price: 490.00,
        maxItems: 100,
        sellerStars: 5,
        reviews: 29,
        article: "6215967",
        detail: "Бадьян (звездчатый анис)",
        status: ['available'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Armenia',
        brand: 'Rawshop',
        freeDelivery: true,
        weight: ['50', '100'],
        attributes: ['spicy']
    },
    {
        image: "orange.jpg",
        name: "Fresh Cranberries",
        type: "Ягоды",
        starsProduct: 4,
        price: 440.00,
        maxItems: 90,
        sellerStars: 4,
        reviews: 22,
        article: "6215968",
        detail: "Свежая клюква",
        status: ['available'],
        deliveryCities: ['Krasnodar'],
        country: 'Russia',
        brand: 'Gainzo',
        freeDelivery: false,
        weight: ['200', '300'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Dried Dates",
        type: "Сухофрукты",
        starsProduct: 5,
        price: 550.00,
        maxItems: 130,
        sellerStars: 5,
        reviews: 37,
        article: "6215969",
        detail: "Финики сушеные",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Armenia',
        brand: 'XBekery',
        freeDelivery: true,
        weight: ['200', '400', '500'],
        attributes: ['noSeed']
    },
    {
        image: "orange.jpg",
        name: "Brazil Nuts",
        type: "Орехи",
        starsProduct: 5,
        price: 1800.00,
        maxItems: 60,
        sellerStars: 5,
        reviews: 28,
        article: "6215970",
        detail: "Бразильский орех",
        status: ['available'],
        deliveryCities: ['Krasnodar', 'Kazan'],
        country: 'Kazakhstan',
        brand: 'Gainzo',
        freeDelivery: true,
        weight: ['200', '300', '500'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Fresh Zucchini",
        type: "Овощи",
        starsProduct: 4,
        price: 180.00,
        maxItems: 200,
        sellerStars: 4,
        reviews: 21,
        article: "6215971",
        detail: "Свежие кабачки",
        status: ['available'],
        deliveryCities: ['Voronezh'],
        country: 'Russia',
        brand: 'Martstore',
        freeDelivery: false,
        weight: ['500', '1000'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Rambutan",
        type: "Экзотика",
        starsProduct: 5,
        price: 990.00,
        maxItems: 50,
        sellerStars: 5,
        reviews: 25,
        article: "6215972",
        detail: "Рамбутан свежий",
        status: ['available', 'onSale'],
        deliveryCities: ['Krasnodar', 'Kazan'],
        country: 'Armenia',
        brand: 'XBekery',
        freeDelivery: true,
        weight: ['300', '500'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Matcha Tea",
        type: "Кофе и чай",
        starsProduct: 5,
        price: 1500.00,
        maxItems: 40,
        sellerStars: 5,
        reviews: 43,
        article: "6215973",
        detail: "Японский чай матча",
        status: ['available'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Armenia',
        brand: 'Rawshop',
        freeDelivery: true,
        weight: ['50', '100'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Nougat",
        type: "Сладости",
        starsProduct: 4,
        price: 420.00,
        maxItems: 100,
        sellerStars: 4,
        reviews: 29,
        article: "6215974",
        detail: "Нуга с орехами",
        status: ['available'],
        deliveryCities: ['Krasnodar'],
        country: 'Kazakhstan',
        brand: 'XBekery',
        freeDelivery: false,
        weight: ['200', '300'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Sweet Potato Chips",
        type: "Чипсы - слайсы",
        starsProduct: 4,
        price: 320.00,
        maxItems: 150,
        sellerStars: 4,
        reviews: 26,
        article: "6215975",
        detail: "Чипсы из батата",
        status: ['available', 'onSale'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Russia',
        brand: 'Martstore',
        freeDelivery: false,
        weight: ['100', '200'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Coriander Seeds",
        type: "Травы и специи",
        starsProduct: 5,
        price: 290.00,
        maxItems: 120,
        sellerStars: 5,
        reviews: 32,
        article: "6215976",
        detail: "Семена кориандра",
        status: ['available'],
        deliveryCities: ['Krasnodar', 'Kazan'],
        country: 'Armenia',
        brand: 'Rawshop',
        freeDelivery: true,
        weight: ['100', '200'],
        attributes: ['spicy']
    },
    {
        image: "orange.jpg",
        name: "Fresh Gooseberries",
        type: "Ягоды",
        starsProduct: 4,
        price: 380.00,
        maxItems: 80,
        sellerStars: 4,
        reviews: 24,
        article: "6215977",
        detail: "Свежий крыжовник",
        status: ['available'],
        deliveryCities: ['Voronezh'],
        country: 'Russia',
        brand: 'Gainzo',
        freeDelivery: false,
        weight: ['200', '300'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Dried Papaya",
        type: "Сухофрукты",
        starsProduct: 5,
        price: 620.00,
        maxItems: 90,
        sellerStars: 5,
        reviews: 35,
        article: "6215978",
        detail: "Сушеная папайя",
        status: ['available', 'onSale'],
        deliveryCities: ['Krasnodar', 'Kazan'],
        country: 'Armenia',
        brand: 'XBekery',
        freeDelivery: true,
        weight: ['200', '300', '500'],
        attributes: []
    },
    {
        image: "orange.jpg",
        name: "Pecan Nuts",
        type: "Орехи",
        starsProduct: 5,
        price: 1600.00,
        maxItems: 70,
        sellerStars: 5,
        reviews: 31,
        article: "6215979",
        detail: "Орехи пекан",
        status: ['available'],
        deliveryCities: ['Voronezh', 'Kazan'],
        country: 'Kazakhstan',
        brand: 'Gainzo',
        freeDelivery: true,
        weight: ['200', '300', '500'],
        attributes: ['fried']
    },
    {
        image: "orange.jpg",
        name: "Fresh Eggplant",
        type: "Овощи",
        starsProduct: 4,
        price: 240.00,
        maxItems: 150,
        sellerStars: 4,
        reviews: 23,
        article: "6215980",
        detail: "Свежие баклажаны",
        status: ['available'],
        deliveryCities: ['Krasnodar'],
        country: 'Russia',
        brand: 'Martstore',
        freeDelivery: false,
        weight: ['500', '1000'],
        attributes: []
    }
].map((product, index) => ({
    ...product,
    id: index + 1
}));

export default {
    name: 'ProductInfo',
    data() {
        return {
            catalog: catalogData
        };
    },
    methods: {
        getCatalog() {
            return this.catalog;
        }
    }
}

export { catalogData };
</script>